spring.application.name=order


spring.datasource.url=jdbc:postgresql://localhost:5432/Order
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.default_schema=orders

# JPA Configuration
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
server.port=8081

# Kafka Configuration
    # Address of the Kafka broker

spring.kafka.bootstrap-servers=172.29.191.138:9092
    # Producer configuration
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
    # Client ID configuration
spring.kafka.client-id=order-service-client
spring.kafka.producer.acks=1
